### ISSUE TITLE
Possibly rename?

### ISSUE THREAD

**Issue by ahutchings** [jurassix/atom-javascript-refactor#5]
The "codemods" bit is arguably an implementation detail, and the "atom" bit could probably be dropped. Looking through my extensions, about half use the "atom-" prefix, so we could go either way.

**Comment by spudly** [comment]
Some ideas:
reactor-imports
refactor-rename
refactor-rename-imports

**Comment by jurassix** [comment]
How to rename an atom package: http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#rename-your-package

**Comment by jurassix** [comment]
Let's finalize the name.
I kinda like the _atom_ bit, seems clearer in google searching, but redundant in apm.

...
atom-javascript-refactor
atom-javascript-refactor-support
...

**Comment by ahutchings** [comment]
How about a compromise? Prefix the GitHub repository name for searchability, but drop the "atom-" prefix from the package.json name field.

Names referencing "imports" and "rename" will be too narrow if we want to add new refactoring functionality later. I like "javascript-refactor", and it's available. "javascript-refactoring" and "js-refactor" are already used by other atom plugins, and "esrefactor" is used for another popular project.

**Comment by jurassix** [comment]
I just updated the README with language that this package is aimed at ES6 Module and CommonJS project refactoring. 

I think _javascript-refactor_ is solid and simple. Imma do it.

😽 😽 😽 😽 😽 😽 😽 😽 😽 😽 😽 😽 😽 😽 😽 😽 😽

**Comment by jurassix** [comment]
closed via v0.5.4
